package model.am.views;

import model.shared.extensions.ExtApplicationModuleImpl;


import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 17 13:01:00 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ExtApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }


    /**
     * Container's getter for EmployeeAttachments1.
     * @return EmployeeAttachments1
     */
    public ExtViewObjectImpl getEmployeeAttachments1() {
        return (ExtViewObjectImpl) findViewObject("EmployeeAttachments1");
    }


    /**
     * Container's getter for empAttach1.
     * @return empAttach1
     */
    public empAttachVOImpl getempAttach1() {
        return (empAttachVOImpl) findViewObject("empAttach1");
    }

    /**
     * Container's getter for empAttach2_1.
     * @return empAttach2_1
     */
    public empAttach2Impl getempAttach2() {
        return (empAttach2Impl) findViewObject("empAttach2");
    }
}

